/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "onERC721Received" | "onboardAgent" | "registry" | "usdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AgentOnboarded"): EventFragment;

  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onboardAgent",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onboardAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace AgentOnboardedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    tba: AddressLike,
    initialFunding: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    tba: string,
    initialFunding: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    tba: string;
    initialFunding: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentFactory extends BaseContract {
  connect(runner?: ContractRunner | null): AgentFactory;
  waitForDeployment(): Promise<this>;

  interface: AgentFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  onboardAgent: TypedContractMethod<
    [
      initialFunding: BigNumberish,
      maxSingleTrade: BigNumberish,
      dailyBudget: BigNumberish,
      autoBuyPrice: BigNumberish,
      autoBuyActive: boolean
    ],
    [[bigint, string] & { agentId: bigint; tba: string }],
    "nonpayable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "onboardAgent"
  ): TypedContractMethod<
    [
      initialFunding: BigNumberish,
      maxSingleTrade: BigNumberish,
      dailyBudget: BigNumberish,
      autoBuyPrice: BigNumberish,
      autoBuyActive: boolean
    ],
    [[bigint, string] & { agentId: bigint; tba: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgentOnboarded"
  ): TypedContractEvent<
    AgentOnboardedEvent.InputTuple,
    AgentOnboardedEvent.OutputTuple,
    AgentOnboardedEvent.OutputObject
  >;

  filters: {
    "AgentOnboarded(uint256,address,address,uint256)": TypedContractEvent<
      AgentOnboardedEvent.InputTuple,
      AgentOnboardedEvent.OutputTuple,
      AgentOnboardedEvent.OutputObject
    >;
    AgentOnboarded: TypedContractEvent<
      AgentOnboardedEvent.InputTuple,
      AgentOnboardedEvent.OutputTuple,
      AgentOnboardedEvent.OutputObject
    >;
  };
}
