/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Escrow {
  export type EscrowRecordStruct = {
    listingId: BigNumberish;
    buyer: AddressLike;
    seller: AddressLike;
    twinId: BigNumberish;
    amount: BigNumberish;
    createdAt: BigNumberish;
    state: BigNumberish;
  };

  export type EscrowRecordStructOutput = [
    listingId: bigint,
    buyer: string,
    seller: string,
    twinId: bigint,
    amount: bigint,
    createdAt: bigint,
    state: bigint
  ] & {
    listingId: bigint;
    buyer: string;
    seller: string;
    twinId: bigint;
    amount: bigint;
    createdAt: bigint;
    state: bigint;
  };
}

export interface EscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIMEOUT"
      | "claimTimeout"
      | "createEscrow"
      | "dispute"
      | "escrowCount"
      | "getEscrow"
      | "marketplace"
      | "refund"
      | "release"
      | "setMarketplace"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowCreated"
      | "EscrowDisputed"
      | "EscrowRefunded"
      | "EscrowReleased"
  ): EventFragment;

  encodeFunctionData(functionFragment: "TIMEOUT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketplace",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "TIMEOUT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "escrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    listingId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    listingId: bigint,
    buyer: string,
    seller: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    listingId: bigint;
    buyer: string;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowDisputedEvent {
  export type InputTuple = [escrowId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [escrowId: bigint, buyer: string];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [escrowId: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [escrowId: bigint, seller: string, amount: bigint];
  export interface OutputObject {
    escrowId: bigint;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Escrow extends BaseContract {
  connect(runner?: ContractRunner | null): Escrow;
  waitForDeployment(): Promise<this>;

  interface: EscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  claimTimeout: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      listingId: BigNumberish,
      buyer: AddressLike,
      seller: AddressLike,
      twinId: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  dispute: TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;

  escrowCount: TypedContractMethod<[], [bigint], "view">;

  getEscrow: TypedContractMethod<
    [escrowId: BigNumberish],
    [Escrow.EscrowRecordStructOutput],
    "view"
  >;

  marketplace: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;

  release: TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;

  setMarketplace: TypedContractMethod<
    [_marketplace: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimTimeout"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      listingId: BigNumberish,
      buyer: AddressLike,
      seller: AddressLike,
      twinId: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dispute"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [escrowId: BigNumberish],
    [Escrow.EscrowRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketplace"
  ): TypedContractMethod<[_marketplace: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowDisputed"
  ): TypedContractEvent<
    EscrowDisputedEvent.InputTuple,
    EscrowDisputedEvent.OutputTuple,
    EscrowDisputedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;

  filters: {
    "EscrowCreated(uint256,uint256,address,address,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowDisputed(uint256,address)": TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;
    EscrowDisputed: TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;

    "EscrowRefunded(uint256,address,uint256)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(uint256,address,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
  };
}
