/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Verifier {
  export type AttestationStruct = {
    node: AddressLike;
    nfcHash: BytesLike;
    finalized: boolean;
  };

  export type AttestationStructOutput = [
    node: string,
    nfcHash: string,
    finalized: boolean
  ] & { node: string; nfcHash: string; finalized: boolean };

  export type NodeStruct = { stake: BigNumberish; active: boolean };

  export type NodeStructOutput = [stake: bigint, active: boolean] & {
    stake: bigint;
    active: boolean;
  };
}

export interface VerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_STAKE"
      | "attestations"
      | "challengeVerification"
      | "deregisterNode"
      | "digitalTwin"
      | "escrow"
      | "getAttestation"
      | "getNode"
      | "marketplace"
      | "nodes"
      | "owner"
      | "registerNode"
      | "renounceOwnership"
      | "reputation"
      | "setReputation"
      | "slash"
      | "submitVerification"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "NodeDeregistered"
      | "NodeRegistered"
      | "NodeSlashed"
      | "OwnershipTransferred"
      | "VerificationChallenged"
      | "VerificationSubmitted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeVerification",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deregisterNode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "digitalTwin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nodes", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerNode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slash",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitVerification",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deregisterNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "digitalTwin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace NodeDeregisteredEvent {
  export type InputTuple = [node: AddressLike, returned: BigNumberish];
  export type OutputTuple = [node: string, returned: bigint];
  export interface OutputObject {
    node: string;
    returned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeRegisteredEvent {
  export type InputTuple = [node: AddressLike, stake: BigNumberish];
  export type OutputTuple = [node: string, stake: bigint];
  export interface OutputObject {
    node: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeSlashedEvent {
  export type InputTuple = [
    node: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [node: string, amount: bigint, reason: string];
  export interface OutputObject {
    node: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationChallengedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    node: AddressLike,
    slashed: BigNumberish
  ];
  export type OutputTuple = [escrowId: bigint, node: string, slashed: bigint];
  export interface OutputObject {
    escrowId: bigint;
    node: string;
    slashed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationSubmittedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    node: AddressLike,
    nfcHash: BytesLike
  ];
  export type OutputTuple = [escrowId: bigint, node: string, nfcHash: string];
  export interface OutputObject {
    escrowId: bigint;
    node: string;
    nfcHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Verifier extends BaseContract {
  connect(runner?: ContractRunner | null): Verifier;
  waitForDeployment(): Promise<this>;

  interface: VerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  attestations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean] & {
        node: string;
        nfcHash: string;
        finalized: boolean;
      }
    ],
    "view"
  >;

  challengeVerification: TypedContractMethod<
    [escrowId: BigNumberish, slashAmt: BigNumberish],
    [void],
    "nonpayable"
  >;

  deregisterNode: TypedContractMethod<[], [void], "nonpayable">;

  digitalTwin: TypedContractMethod<[], [string], "view">;

  escrow: TypedContractMethod<[], [string], "view">;

  getAttestation: TypedContractMethod<
    [escrowId: BigNumberish],
    [Verifier.AttestationStructOutput],
    "view"
  >;

  getNode: TypedContractMethod<
    [nodeAddr: AddressLike],
    [Verifier.NodeStructOutput],
    "view"
  >;

  marketplace: TypedContractMethod<[], [string], "view">;

  nodes: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { stake: bigint; active: boolean }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerNode: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputation: TypedContractMethod<[], [string], "view">;

  setReputation: TypedContractMethod<
    [_reputation: AddressLike],
    [void],
    "nonpayable"
  >;

  slash: TypedContractMethod<
    [node: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  submitVerification: TypedContractMethod<
    [escrowId: BigNumberish, nfcHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean] & {
        node: string;
        nfcHash: string;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "challengeVerification"
  ): TypedContractMethod<
    [escrowId: BigNumberish, slashAmt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deregisterNode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "digitalTwin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [escrowId: BigNumberish],
    [Verifier.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNode"
  ): TypedContractMethod<
    [nodeAddr: AddressLike],
    [Verifier.NodeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nodes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { stake: bigint; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerNode"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setReputation"
  ): TypedContractMethod<[_reputation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slash"
  ): TypedContractMethod<
    [node: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitVerification"
  ): TypedContractMethod<
    [escrowId: BigNumberish, nfcHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "NodeDeregistered"
  ): TypedContractEvent<
    NodeDeregisteredEvent.InputTuple,
    NodeDeregisteredEvent.OutputTuple,
    NodeDeregisteredEvent.OutputObject
  >;
  getEvent(
    key: "NodeRegistered"
  ): TypedContractEvent<
    NodeRegisteredEvent.InputTuple,
    NodeRegisteredEvent.OutputTuple,
    NodeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "NodeSlashed"
  ): TypedContractEvent<
    NodeSlashedEvent.InputTuple,
    NodeSlashedEvent.OutputTuple,
    NodeSlashedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VerificationChallenged"
  ): TypedContractEvent<
    VerificationChallengedEvent.InputTuple,
    VerificationChallengedEvent.OutputTuple,
    VerificationChallengedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationSubmitted"
  ): TypedContractEvent<
    VerificationSubmittedEvent.InputTuple,
    VerificationSubmittedEvent.OutputTuple,
    VerificationSubmittedEvent.OutputObject
  >;

  filters: {
    "NodeDeregistered(address,uint256)": TypedContractEvent<
      NodeDeregisteredEvent.InputTuple,
      NodeDeregisteredEvent.OutputTuple,
      NodeDeregisteredEvent.OutputObject
    >;
    NodeDeregistered: TypedContractEvent<
      NodeDeregisteredEvent.InputTuple,
      NodeDeregisteredEvent.OutputTuple,
      NodeDeregisteredEvent.OutputObject
    >;

    "NodeRegistered(address,uint256)": TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;
    NodeRegistered: TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;

    "NodeSlashed(address,uint256,string)": TypedContractEvent<
      NodeSlashedEvent.InputTuple,
      NodeSlashedEvent.OutputTuple,
      NodeSlashedEvent.OutputObject
    >;
    NodeSlashed: TypedContractEvent<
      NodeSlashedEvent.InputTuple,
      NodeSlashedEvent.OutputTuple,
      NodeSlashedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VerificationChallenged(uint256,address,uint256)": TypedContractEvent<
      VerificationChallengedEvent.InputTuple,
      VerificationChallengedEvent.OutputTuple,
      VerificationChallengedEvent.OutputObject
    >;
    VerificationChallenged: TypedContractEvent<
      VerificationChallengedEvent.InputTuple,
      VerificationChallengedEvent.OutputTuple,
      VerificationChallengedEvent.OutputObject
    >;

    "VerificationSubmitted(uint256,address,bytes32)": TypedContractEvent<
      VerificationSubmittedEvent.InputTuple,
      VerificationSubmittedEvent.OutputTuple,
      VerificationSubmittedEvent.OutputObject
    >;
    VerificationSubmitted: TypedContractEvent<
      VerificationSubmittedEvent.InputTuple,
      VerificationSubmittedEvent.OutputTuple,
      VerificationSubmittedEvent.OutputObject
    >;
  };
}
