/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AgentAccountInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorisedExecutors"
      | "autoBuyPolicy"
      | "chainId"
      | "dailyBudget"
      | "dailySpent"
      | "dayStart"
      | "execute"
      | "executeAutoBuy"
      | "executeUSDCTransfer"
      | "isValidSigner"
      | "maxSingleTrade"
      | "onERC721Received"
      | "owner"
      | "setAutoBuyPolicy"
      | "setExecutor"
      | "setPolicy"
      | "state"
      | "supportsInterface"
      | "token"
      | "tokenContract"
      | "tokenId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoBuyPolicyUpdated"
      | "Executed"
      | "ExecutorUpdated"
      | "PolicyUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorisedExecutors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "autoBuyPolicy",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dailyBudget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailySpent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dayStart", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAutoBuy",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeUSDCTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSigner",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxSingleTrade",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAutoBuyPolicy",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicy",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tokenId", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "authorisedExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoBuyPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dailyBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dailySpent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dayStart", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeAutoBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeUSDCTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSingleTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAutoBuyPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenId", data: BytesLike): Result;
}

export namespace AutoBuyPolicyUpdatedEvent {
  export type InputTuple = [maxPrice: BigNumberish, active: boolean];
  export type OutputTuple = [maxPrice: bigint, active: boolean];
  export interface OutputObject {
    maxPrice: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutedEvent {
  export type InputTuple = [
    target: AddressLike,
    value: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [target: string, value: bigint, data: string];
  export interface OutputObject {
    target: string;
    value: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorUpdatedEvent {
  export type InputTuple = [executor: AddressLike, authorised: boolean];
  export type OutputTuple = [executor: string, authorised: boolean];
  export interface OutputObject {
    executor: string;
    authorised: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyUpdatedEvent {
  export type InputTuple = [
    maxSingleTrade: BigNumberish,
    dailyBudget: BigNumberish
  ];
  export type OutputTuple = [maxSingleTrade: bigint, dailyBudget: bigint];
  export interface OutputObject {
    maxSingleTrade: bigint;
    dailyBudget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentAccount extends BaseContract {
  connect(runner?: ContractRunner | null): AgentAccount;
  waitForDeployment(): Promise<this>;

  interface: AgentAccountInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorisedExecutors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  autoBuyPolicy: TypedContractMethod<
    [],
    [[bigint, boolean] & { maxPrice: bigint; active: boolean }],
    "view"
  >;

  chainId: TypedContractMethod<[], [bigint], "view">;

  dailyBudget: TypedContractMethod<[], [bigint], "view">;

  dailySpent: TypedContractMethod<[], [bigint], "view">;

  dayStart: TypedContractMethod<[], [bigint], "view">;

  execute: TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      arg3: BigNumberish
    ],
    [string],
    "payable"
  >;

  executeAutoBuy: TypedContractMethod<
    [
      marketplace: AddressLike,
      escrow: AddressLike,
      usdc: AddressLike,
      listingId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  executeUSDCTransfer: TypedContractMethod<
    [usdc: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  isValidSigner: TypedContractMethod<
    [signer: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;

  maxSingleTrade: TypedContractMethod<[], [bigint], "view">;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setAutoBuyPolicy: TypedContractMethod<
    [_maxPrice: BigNumberish, _active: boolean],
    [void],
    "nonpayable"
  >;

  setExecutor: TypedContractMethod<
    [executor: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;

  setPolicy: TypedContractMethod<
    [_maxSingleTrade: BigNumberish, _dailyBudget: BigNumberish],
    [void],
    "nonpayable"
  >;

  state: TypedContractMethod<[], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  token: TypedContractMethod<[], [[bigint, string, bigint]], "view">;

  tokenContract: TypedContractMethod<[], [string], "view">;

  tokenId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorisedExecutors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "autoBuyPolicy"
  ): TypedContractMethod<
    [],
    [[bigint, boolean] & { maxPrice: bigint; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "chainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyBudget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailySpent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dayStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      arg3: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeAutoBuy"
  ): TypedContractMethod<
    [
      marketplace: AddressLike,
      escrow: AddressLike,
      usdc: AddressLike,
      listingId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeUSDCTransfer"
  ): TypedContractMethod<
    [usdc: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isValidSigner"
  ): TypedContractMethod<
    [signer: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxSingleTrade"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAutoBuyPolicy"
  ): TypedContractMethod<
    [_maxPrice: BigNumberish, _active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setExecutor"
  ): TypedContractMethod<
    [executor: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPolicy"
  ): TypedContractMethod<
    [_maxSingleTrade: BigNumberish, _dailyBudget: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [[bigint, string, bigint]], "view">;
  getFunction(
    nameOrSignature: "tokenContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AutoBuyPolicyUpdated"
  ): TypedContractEvent<
    AutoBuyPolicyUpdatedEvent.InputTuple,
    AutoBuyPolicyUpdatedEvent.OutputTuple,
    AutoBuyPolicyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorUpdated"
  ): TypedContractEvent<
    ExecutorUpdatedEvent.InputTuple,
    ExecutorUpdatedEvent.OutputTuple,
    ExecutorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyUpdated"
  ): TypedContractEvent<
    PolicyUpdatedEvent.InputTuple,
    PolicyUpdatedEvent.OutputTuple,
    PolicyUpdatedEvent.OutputObject
  >;

  filters: {
    "AutoBuyPolicyUpdated(uint256,bool)": TypedContractEvent<
      AutoBuyPolicyUpdatedEvent.InputTuple,
      AutoBuyPolicyUpdatedEvent.OutputTuple,
      AutoBuyPolicyUpdatedEvent.OutputObject
    >;
    AutoBuyPolicyUpdated: TypedContractEvent<
      AutoBuyPolicyUpdatedEvent.InputTuple,
      AutoBuyPolicyUpdatedEvent.OutputTuple,
      AutoBuyPolicyUpdatedEvent.OutputObject
    >;

    "Executed(address,uint256,bytes)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;

    "ExecutorUpdated(address,bool)": TypedContractEvent<
      ExecutorUpdatedEvent.InputTuple,
      ExecutorUpdatedEvent.OutputTuple,
      ExecutorUpdatedEvent.OutputObject
    >;
    ExecutorUpdated: TypedContractEvent<
      ExecutorUpdatedEvent.InputTuple,
      ExecutorUpdatedEvent.OutputTuple,
      ExecutorUpdatedEvent.OutputObject
    >;

    "PolicyUpdated(uint256,uint256)": TypedContractEvent<
      PolicyUpdatedEvent.InputTuple,
      PolicyUpdatedEvent.OutputTuple,
      PolicyUpdatedEvent.OutputObject
    >;
    PolicyUpdated: TypedContractEvent<
      PolicyUpdatedEvent.InputTuple,
      PolicyUpdatedEvent.OutputTuple,
      PolicyUpdatedEvent.OutputObject
    >;
  };
}
